### ISSUE TITLE
Problems whith thumbs

### ISSUE THREAD

**Issue by diegoalfr** [KarolisMart/RSIG#1]
Hello i´m having problems with the thumbnails creation. My joomla website is under PHP 7 and I suspect the problem is the php version. You can check the problem in my website: www.diegoalonso.es
![captura de pantalla 2016-08-19 a las 11 25 52](https://cloud.githubusercontent.com/assets/21122205/17805976/547ad7c2-6602-11e6-985b-9291facb91f2.png)

**Comment by KarolisMart** [comment]
Hi, could you turn on error reporting and paste errors here? Also System information text file would also help

**Comment by diegoalfr** [comment]
Hi KarolisMart. Here is the system info.
[systeminfo-2016-08-19T16_15_19+00_00.txt](https://github.com/KarolisMart/RSIG/files/427426/systeminfo-2016-08-19T16_15_19.00_00.txt)

**Comment by KarolisMart** [comment]
Could you also turn on error reporting in Global Configuration -> Server Settings and check if any errors are shown when you clear cache and refresh the gallery page.
Are any RSIG files generated in the cache folder?

**Comment by diegoalfr** [comment]
The plugin can not create a folder in the cache folder. I have change the folder permisions to 777 but the plugin can not create any folder.

**Comment by diegoalfr** [comment]
You can see now the error reporting in the web. Please help me

**Comment by KarolisMart** [comment]
Some thumbs seem to get generated, but I'm not yet sure why, I'll take a look tomorrow

**Comment by KarolisMart** [comment]
I had some problems replicating the issue, seemed to work fine on my vm with php 7. If i fail to find the problem tomorrow I could add static thumbnail support, maybe even this week.

**Comment by KarolisMart** [comment]
Well I failed to replicate the problem on php 7.0.11-dev and Joomla 3.6.2. And your php configuration file seems normal, maybe realpath_cache_size is low, but that should only affect performance when generating images, but shouldn't cause a failure of thumb generation.
You could try disabling other plugins and playing around with server settings, but if that doesn't work as I said i could add static thumbnail support (you could create thumb folder inside gallery folder and add pregenerated thumbnails there), maybe this weekend.

**Comment by diegoalfr** [comment]
Now i changed the php version to 5.3 in my webhosting and the problem is the same. The thumbnails don´t generated in the cache folder.

**Comment by KarolisMart** [comment]
Hi, sorry i could only come back to you now. Could you try installing [this version](https://martinkus.eu/RSIG-debug.zip), it has some errors unmuted and a possible fix. Turn on error reporting when trying.

**Comment by diegoalfr** [comment]
Don´t work. The thumbs don´t generated. 

http://www.diegoalonso.es/el-blog/bodas/217-preboda-en-coruna-de-nuria-fabian.html

**Comment by KarolisMart** [comment]
Does php error reporting say anything new?

**Comment by diegoalfr** [comment]
Nothing new. I have checked the cache folder and is empty.

**Comment by KarolisMart** [comment]
In [v0.3](https://github.com/KarolisMart/RSIG/tree/v0.3) I added custom/pregenerated thumbnail support that could solve this issue.
