### ISSUE TITLE
Big thumbnails with wrong aspect ratio

### ISSUE THREAD

**Issue by otpfiste** [KarolisMart/RSIG#3]
Hi Karolis Mart,

if you have a small containing box and big thumbnails "max-width: 100%" correctly limits the thumbnail width but distorts also the aspect ratio. To correct that in template.css could you please add to .rsig-img class "height: auto !important", it would be:

.rsig-img{display: inline-block; max-width: 100%; height: auto !important}

Best Regards,
Oliver Pfister

**Comment by KarolisMart** [comment]
Hi Oliver,

Sorry for taking a while to come back to you.
I'll test out that change next week and merge it.

Thanks for the report
Karolis

**Comment by KarolisMart** [comment]
Hi @otpfiste,

I can't add the `!important` flag as that causes problems with Masonry layout and it could interfere with setting maximum height of thumbnails in RSIG settings. 
I did add the `height: auto` part. This seems to work fine.

Can you test the [updated version](https://github.com/KarolisMart/RSIG/archive/master.zip) to see if it works fine now?

I actually wasn't able to replicate your issue without the `height: auto`. What browser and what RSIG parameters were you using? It would be best if you could share a link to a page experiencing the issue if the updated version does not work for you.

**Comment by otpfiste** [comment]
Hi Karolis,

I installed latest master, no changes. The issue I'm speaking about happens with the RSIG fluid layout.

The problem is that height: auto without !important cannot override the static height set for the image tag, as this latter one has higher priority. I setup a small example page with the problem, try to shrink any browser window (Firefox, Chrome, Opera, ...) and you will see that it stretches the thumbs without maintaining the aspect ratio:

https://www.contaware.com/index.php?option=com_rspagebuilder&view=page&id=1

Regards,
Oliver

**Comment by KarolisMart** [comment]
Thanks for the link @otpfiste. I see the problem now.

I think `object-fit: contain;` is the most elegant solution. Seems to work fine with your test page when added in browser. IE doesn't support it, but it shouldn't matter as it's usage is low and in this case the problem only really affects mobile devices. 

I updated the code accordingly. See if [this](https://github.com/KarolisMart/RSIG/archive/master.zip) works.

**Comment by otpfiste** [comment]
Thanks for the fast replay, now it centers inside the reserved image space and that is not so nice because of the big gaps between the images, see the same like as above.

To solve the problem we could stick with height: auto and remove width and height from the img style. But then the retina trick with 2X resolution would not work anymore. So the only true solution I see is to use height: auto !important but only for the fluid layout. So that would mean having 3 different template.css, one for fluid, another for grid and a last one for masonry.

What do you think?

**Comment by KarolisMart** [comment]
@otpfiste I reworked some things. Should be good now.  [Check it  out.](https://github.com/KarolisMart/RSIG/archive/master.zip)
Masonry will now work well with small width screens too.

**Comment by otpfiste** [comment]
Updated your latest master in my test page and it works great.

Thanks a lot for your excellent work,
Oliver

**Comment by KarolisMart** [comment]
Glad to hear it!
